/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Pc
 */
import dao.AppointmentDAO;
import dao.DentistDAO;
import dao.TreatmentTypeDAO;
import model.Appointment;
import model.Dentist;
import model.TreatmentType;
import model.User;
import java.util.List;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

public class AppointmentForm extends javax.swing.JFrame {

    private User currentUser;

    public AppointmentForm() {
        initComponents();
        setLocationRelativeTo(null);
        loadDentists();
        loadTreatmentTypes();
    }

    public AppointmentForm(User currentUser) {
        this();
        this.currentUser = currentUser;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlForm = new javax.swing.JPanel();
        lblAppointmentNo = new javax.swing.JLabel();
        txtAppointmentNo = new javax.swing.JTextField();
        lblPatientName = new javax.swing.JLabel();
        txtPatientName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblDentist = new javax.swing.JLabel();
        cmbDentist = new javax.swing.JComboBox();
        lblTreatment = new javax.swing.JLabel();
        cmbTreatment = new javax.swing.JComboBox();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        timePicker = new com.github.lgooddatepicker.components.TimePicker();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register New Appointment");

        pnlForm.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAppointmentNo.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblAppointmentNo.setText("Appointment Number:");
        pnlForm.add(lblAppointmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 79, -1, -1));

        txtAppointmentNo.setColumns(20);
        txtAppointmentNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAppointmentNoActionPerformed(evt);
            }
        });
        pnlForm.add(txtAppointmentNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));

        lblPatientName.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblPatientName.setText("Patient Name:");
        pnlForm.add(lblPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 128, -1, -1));

        txtPatientName.setColumns(20);
        pnlForm.add(txtPatientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, -1, -1));

        lblAddress.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblAddress.setText("Address:");
        pnlForm.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 174, -1, -1));

        txtAddress.setColumns(20);
        pnlForm.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        lblContact.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblContact.setText("Contact Number:");
        pnlForm.add(lblContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 217, -1, -1));

        txtContact.setColumns(20);
        pnlForm.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        lblDentist.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblDentist.setText("Dentist:");
        pnlForm.add(lblDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 263, -1, -1));
        pnlForm.add(cmbDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 160, -1));

        lblTreatment.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblTreatment.setText("Treatment Type:");
        pnlForm.add(lblTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 316, -1, -1));
        pnlForm.add(cmbTreatment, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 160, -1));

        lblDate.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblDate.setText("Appointment Date (YYYY-MM-DD):");
        pnlForm.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 356, -1, -1));

        lblTime.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblTime.setText("Appointment Time (HH:MM):");
        pnlForm.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 406, -1, -1));

        btnSave.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnSave.setText("Save");
        btnSave.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(51, 255, 255), null, new java.awt.Color(0, 153, 255)));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlForm.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 72, 29));

        btnClear.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnClear.setText("Clear all");
        btnClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 102), new java.awt.Color(204, 0, 0)));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlForm.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 64, 29));

        btnClose.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlForm.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, -1, -1));

        lblTitle.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblTitle.setText("REGISTER NEW APPOINTMENT");
        pnlForm.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        pnlForm.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 150, -1));
        pnlForm.add(timePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 150, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/BG - Copy.png"))); // NOI18N
        pnlForm.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDentists() {
        cmbDentist.removeAllItems();
        List<Dentist> list = new DentistDAO().getAllDentists();
        for (Dentist d : list) {
            cmbDentist.addItem(d);
        }
    }

    private void loadTreatmentTypes() {
        cmbTreatment.removeAllItems();
        List<TreatmentType> list = new TreatmentTypeDAO().getAllTreatmentTypes();
        for (TreatmentType t : list) {
            cmbTreatment.addItem(t);
        }
    }

    private boolean validateAppointment() {
     String no = txtAppointmentNo.getText().trim();
     String name = txtPatientName.getText().trim();
     String address = txtAddress.getText().trim();
     String contact = txtContact.getText().trim();
        
        if (no.isEmpty() || name.isEmpty() || address.isEmpty() || contact.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill all fields.");
            return false;
        }
        
        if (!no.matches("[A-Za-z0-9-]{3,20}")) {
            JOptionPane.showMessageDialog(this, "Invalid appointment number.");
            return false;
        }
        
        if (!name.matches("[A-Za-z .'-]{2,60}")) {
            JOptionPane.showMessageDialog(this, "Enter a valid patient name.");
            return false;
        }
        
        if (!contact.matches("0\\d{9}")) {
            JOptionPane.showMessageDialog(this, "Contact number must contain 10 digits and start with 0.");
            return false;
        }
        
        if (datePicker.getDate() == null) {
            JOptionPane.showMessageDialog(this, "Please select appointment date.");
            return false;
        }

        String date = datePicker.getDate().toString();
        if (timePicker.getTime() == null) {
            JOptionPane.showMessageDialog(this, "Please select appointment time.");
            return false;
        }

        String time = timePicker.getTime().toString();
        if (cmbDentist.getSelectedItem() == null || cmbTreatment.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Select dentist and treatment type.");
            return false;
            
        }
        
        return true;
    }

    private void clearFields() {
        txtAppointmentNo.setText("");
        txtPatientName.setText("");
        txtAddress.setText("");
        txtContact.setText("");
        
        if (cmbDentist.getItemCount() > 0) {
            cmbDentist.setSelectedIndex(0);
        }
        
        if (cmbTreatment.getItemCount() > 0) {
            cmbTreatment.setSelectedIndex(0);
        }
    }

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
    String no = txtAppointmentNo.getText().trim();
    String name = txtPatientName.getText().trim();
    String address = txtAddress.getText().trim();
    String contact = txtContact.getText().trim();

    if (no.isEmpty() || name.isEmpty() || address.isEmpty() || contact.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return;
    }

    if (!no.matches("[A-Za-z0-9-]{3,20}")) {
        JOptionPane.showMessageDialog(this,
                "Appointment number must contain 3-20 letters, numbers or hyphens.");
        return;
    }

    if (!name.matches("[A-Za-z .'-]{2,60}")) {
        JOptionPane.showMessageDialog(this, "Enter a valid patient name.");
        return;
    }

    if (!contact.matches("0\\d{9}")) {
        JOptionPane.showMessageDialog(this,
                "Contact number must contain 10 digits and start with 0.");
        return;
    }

    LocalDate selectedDate = datePicker.getDate();

    if (selectedDate == null) {
        JOptionPane.showMessageDialog(this,
                "Please select an appointment date.");
        return;
    }

    if (selectedDate.isBefore(LocalDate.now())) {
        JOptionPane.showMessageDialog(this,
                "Appointment date cannot be in the past.");
        return;
    }

    LocalTime selectedTime = timePicker.getTime();

    if (selectedTime == null) {
        JOptionPane.showMessageDialog(this,
                "Please select an appointment time.");
        return;
    }

    String date = selectedDate.format(
            DateTimeFormatter.ofPattern("yyyy-MM-dd"));

    String time = selectedTime.format(
            DateTimeFormatter.ofPattern("HH:mm"));

    if (cmbDentist.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a dentist.");
        return;
    }

    if (cmbTreatment.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a treatment type.");
        return;
    }

    Dentist dentist = (Dentist) cmbDentist.getSelectedItem();
    TreatmentType treatment =
            (TreatmentType) cmbTreatment.getSelectedItem();

    AppointmentDAO dao = new AppointmentDAO();

    if (dao.appointmentExists(no)) {
        JOptionPane.showMessageDialog(this,
                "This appointment number already exists.");
        return;
    }

    if (!dao.isDentistAvailable(
            dentist.getDentistId(), date, time)) {

        JOptionPane.showMessageDialog(this,
                "Selected dentist is not available on this date/time."
                + "\nPlease check the Dentist Schedule.");
        return;
    }

    if (dao.isDentistBooked(
            dentist.getDentistId(), date, time)) {

        JOptionPane.showMessageDialog(this,
                "This dentist already has an appointment "
                + "at the selected time.");
        return;
    }

    Appointment appointment = new Appointment();

    appointment.setAppointmentNo(no);
    appointment.setPatientName(name);
    appointment.setAddress(address);
    appointment.setContactNo(contact);

    appointment.setDentistId(dentist.getDentistId());
    appointment.setTreatmentTypeId(
            treatment.getTreatmentTypeId());

    appointment.setAppointmentDate(date);
    appointment.setAppointmentTime(time);
    appointment.setCreatedBy(currentUser.getUserId());



    if (dao.addAppointment(appointment)) {

        JOptionPane.showMessageDialog(this,"Appointment registered successfully.");

        txtAppointmentNo.setText("");
        txtPatientName.setText("");
        txtAddress.setText("");
        txtContact.setText("");

        datePicker.clear();
        timePicker.clear();

        if (cmbDentist.getItemCount() > 0) {
            cmbDentist.setSelectedIndex(0);
        }

        if (cmbTreatment.getItemCount() > 0) {
            cmbTreatment.setSelectedIndex(0);
        }

    } 
    else {

        JOptionPane.showMessageDialog(this,
                "Unable to save appointment.",
                "Error",
                JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSaveActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtAppointmentNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAppointmentNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAppointmentNoActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbDentist;
    private javax.swing.JComboBox cmbTreatment;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAppointmentNo;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDentist;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTreatment;
    private javax.swing.JPanel pnlForm;
    private com.github.lgooddatepicker.components.TimePicker timePicker;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAppointmentNo;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
