/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Pc
 */
import dao.DentistAvailabilityDAO;
import dao.DentistDAO;
import model.Dentist;
import model.DentistAvailability;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class DentistScheduleForm extends javax.swing.JFrame {

    public DentistScheduleForm() {
        initComponents();
        setLocationRelativeTo(null);
        setupTable();
        loadDentists();
        loadSchedule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDentist = new javax.swing.JLabel();
        cmbDentist = new javax.swing.JComboBox();
        btnView = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSchedule = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dentist Schedule");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDentist.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblDentist.setText("Select Dentist:");
        jPanel1.add(lblDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 103, -1, -1));
        jPanel1.add(cmbDentist, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 100, 178, -1));

        btnView.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnView.setText("View Schedule");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel1.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 100, -1, -1));

        btnClose.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 28, -1, -1));

        jScrollPane1.setViewportView(tblSchedule);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 146, 654, 280));

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        jLabel1.setText("Dentist Schedule");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 23, -1, -1));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 100, 53, 41));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupTable() {
        tblSchedule.setModel(new DefaultTableModel(new Object[]{"ID", "Dentist", "Date", "Start Time", "End Time", "Available"}, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        });
    }

    private void loadDentists() {
        cmbDentist.removeAllItems();
        cmbDentist.addItem("All Dentists");
        for (Dentist d : new DentistDAO().getAllDentists()) {
            cmbDentist.addItem(d);
        }
    }

    private void loadSchedule() {
        DefaultTableModel model = (DefaultTableModel) tblSchedule.getModel();
        model.setRowCount(0);
        Object selected = cmbDentist.getSelectedItem();
        List<DentistAvailability> list;
        DentistAvailabilityDAO dao = new DentistAvailabilityDAO();
        
        if (selected instanceof Dentist) {
            list = dao.getByDentist(((Dentist) selected).getDentistId());
        } 
        
        else {
            list = dao.getAll();
        }
        
        for (DentistAvailability a : list) {
            model.addRow(new Object[]{a.getAvailabilityId(), a.getDentistName(), a.getAvailableDate(), a.getStartTime(),
            a.getEndTime(), a.isAvailable() ? "Yes" : "No"});
        }
    }
    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        loadSchedule();
    }//GEN-LAST:event_btnViewActionPerformed
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadSchedule();
    }//GEN-LAST:event_btnRefreshActionPerformed
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox cmbDentist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDentist;
    private javax.swing.JTable tblSchedule;
    // End of variables declaration//GEN-END:variables
}
