/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Pc
 */
import dao.DentistAvailabilityDAO;
import model.DentistAvailability;
import model.User;
import java.time.LocalDate;
import java.time.LocalTime;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class ManageAvailabilityForm extends javax.swing.JFrame {

    private User currentUser;

    public ManageAvailabilityForm() {
        initComponents();
        setLocationRelativeTo(null);
        setupTable();
    }

    public ManageAvailabilityForm(User currentUser) {
        this();
        this.currentUser = currentUser;
        loadAvailability();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlButtons = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAvailability = new javax.swing.JTable();
        pnlTop = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblStartTime = new javax.swing.JLabel();
        lblEndTime = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();
        startTimePicker = new com.github.lgooddatepicker.components.TimePicker();
        endTimePicker = new com.github.lgooddatepicker.components.TimePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Available Dates & Time Slots");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setText("Add Availability");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlButtons.add(btnAdd);

        btnDelete.setText("Delete Selected");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlButtons.add(btnDelete);

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        pnlButtons.add(btnClear);

        jPanel1.add(pnlButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, 360, -1));

        jScrollPane1.setViewportView(tblAvailability);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 604, 190));

        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Felix Titling", 0, 24)); // NOI18N
        lblTitle.setText("MANAGE AVAILABLE DATES & TIME");
        pnlTop.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, 47));

        lblDate.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblDate.setText("Available Date (YYYY-MM-DD):");
        pnlTop.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        lblStartTime.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblStartTime.setText("Start Time (HH:MM):");
        pnlTop.add(lblStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 132, -1));

        lblEndTime.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        lblEndTime.setText("End Time (HH:MM):");
        pnlTop.add(lblEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, -1, 18));

        btnClose.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        pnlTop.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Pictures/refresh.png"))); // NOI18N
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        pnlTop.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 40, 40));
        pnlTop.add(datePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, -1, -1));
        pnlTop.add(startTimePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 140, -1));
        pnlTop.add(endTimePicker, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 140, -1));

        jPanel1.add(pnlTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 3, -1, 210));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void setupTable() {
        tblAvailability.setModel(new DefaultTableModel(new Object[]{"ID", "Date", "Start Time", "End Time", "Available"}, 0) {
            public boolean isCellEditable(int r, int c) {
                return false;
            }
        });
    }

    private void loadAvailability() {
        if (currentUser == null || currentUser.getDentistId() == null) {
            return;
        }
        
        DefaultTableModel m = (DefaultTableModel) tblAvailability.getModel();
        m.setRowCount(0);
        
        for (DentistAvailability a : new DentistAvailabilityDAO().getByDentist(currentUser.getDentistId())) {
            m.addRow(new Object[]{a.getAvailabilityId(), a.getAvailableDate(), a.getStartTime(), a.getEndTime(), a.isAvailable() ? "Yes" : "No"});
        }
    }

    private void clearFields() {
        datePicker.clear();
        startTimePicker.clear();
        endTimePicker.clear();
    }
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    if (currentUser == null || currentUser.getDentistId() == null) {
        JOptionPane.showMessageDialog(this,
                "Please login as a dentist first.");
        return;
    }

    // Get date
    if (datePicker.getDate() == null) {
        JOptionPane.showMessageDialog(this,
                "Please select an available date.");
        return;
    }

    // Get start time
    if (startTimePicker.getTime() == null) {
        JOptionPane.showMessageDialog(this,
                "Please select a start time.");
        return;
    }

    // Get end time
    if (endTimePicker.getTime() == null) {
        JOptionPane.showMessageDialog(this,
                "Please select an end time.");
        return;
    }

    LocalDate d = datePicker.getDate();
    LocalTime s = startTimePicker.getTime();
    LocalTime e = endTimePicker.getTime();

    String date = d.toString();
    String start = s.toString();
    String end = e.toString();

    // Date cannot be in the past
    if (d.isBefore(LocalDate.now())) {
        JOptionPane.showMessageDialog(this,
                "Available date cannot be in the past.");
        return;
    }

    // Start must be before end
    if (!s.isBefore(e)) {
        JOptionPane.showMessageDialog(this,
                "Start time must be before end time.");
        return;
    }

    // Check existing availability
    List<DentistAvailability> existing =
            new DentistAvailabilityDAO()
                    .getByDentist(currentUser.getDentistId());

    for (DentistAvailability old : existing) {

        if (date.equals(old.getAvailableDate())) {

            LocalTime os = LocalTime.parse(old.getStartTime());
            LocalTime oe = LocalTime.parse(old.getEndTime());

            if (s.isBefore(oe) && e.isAfter(os)) {
                JOptionPane.showMessageDialog(this,
                        "This time overlaps an existing availability slot.");
                return;
            }
        }
    }

    // Create availability
    DentistAvailability a = new DentistAvailability();

    a.setDentistId(currentUser.getDentistId());
    a.setAvailableDate(date);
    a.setStartTime(start);
    a.setEndTime(end);
    a.setAvailable(true);

    // Save to database
    if (new DentistAvailabilityDAO().addAvailability(a)) {

        JOptionPane.showMessageDialog(this,
                "Availability added successfully.");

        clearFields();
        loadAvailability();

    } else {

        JOptionPane.showMessageDialog(this,
                "Unable to add availability.");
    }

    }//GEN-LAST:event_btnAddActionPerformed
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tblAvailability.getSelectedRow();
        
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Select an availability record.");
            return;
        }
        int id = Integer.parseInt(tblAvailability.getValueAt(row, 0).toString());
        if (JOptionPane.showConfirmDialog(this, "Delete selected availability?", "Confirm", JOptionPane.YES_NO_OPTION) != JOptionPane.YES_OPTION) {
            return;
        }
        
        if (new DentistAvailabilityDAO().deleteAvailability(id, currentUser.getDentistId())) {
            JOptionPane.showMessageDialog(this, "Availability deleted.");
            loadAvailability();
        } 
        
        else
            JOptionPane.showMessageDialog(this, "Unable to delete availability.");
    }//GEN-LAST:event_btnDeleteActionPerformed
    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        loadAvailability();
    }//GEN-LAST:event_btnRefreshActionPerformed
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearFields();
    }//GEN-LAST:event_btnClearActionPerformed
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private com.github.lgooddatepicker.components.TimePicker endTimePicker;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblEndTime;
    private javax.swing.JLabel lblStartTime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlButtons;
    private javax.swing.JPanel pnlTop;
    private com.github.lgooddatepicker.components.TimePicker startTimePicker;
    private javax.swing.JTable tblAvailability;
    // End of variables declaration//GEN-END:variables
}
